import { redirect } from "next/navigation";
import { createClient } from "@/utils/supabase/server";
import { AnalysisDisplay } from "./analysis-display";
import type { AnalysisData, DeepAnalysisData } from "@/app/api/analyze/route";
import type { Metadata } from "next";

type Props = { params: Promise<{ id: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const supabase = await createClient();
  const { data } = await supabase
    .from("projects")
    .select("title, analysis")
    .eq("id", id)
    .single();

  const title = data?.title ?? "Analysis";
  return {
    title: `${title} — Analysis`,
    description: "Product intelligence report generated by Axiom.",
  };
}

export default async function AnalysisPage({ params }: Props) {
  const { id } = await params;
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { data: project } = await supabase
    .from("projects")
    .select("id, title, raw_idea, analysis, deep_analysis, input_mode")
    .eq("id", id)
    .eq("user_id", user.id)
    .single();

  if (!project) redirect("/dashboard");
  if (!project.analysis) redirect(`/project/${id}`);

  return (
    <AnalysisDisplay
      projectId={project.id}
      projectTitle={project.title ?? "Product Analysis"}
      projectIdea={project.raw_idea ?? ""}
      analysis={project.analysis as AnalysisData}
      deepAnalysis={(project.deep_analysis ?? null) as DeepAnalysisData | null}
      inputMode={(project.input_mode as "idea" | "code" | "github") ?? "idea"}
    />
  );
}
