import Link from "next/link";

export const metadata = { title: "Terms of Service – Axiom" };

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--vs-bg)", color: "var(--vs-text)" }}>
      {/* Ambient */}
      <div aria-hidden="true" style={{ position: "fixed", top: "-15%", left: "50%", transform: "translateX(-50%)", width: 600, height: 600, borderRadius: "50%", background: "radial-gradient(circle, rgba(124,58,237,0.12) 0%, transparent 70%)", filter: "blur(80px)", pointerEvents: "none", zIndex: 0 }} />

      {/* Navbar */}
      <nav style={{ position: "sticky", top: 0, zIndex: 50, padding: "0 2rem", background: "rgba(3,0,20,0.88)", backdropFilter: "blur(24px)", WebkitBackdropFilter: "blur(24px)", borderBottom: "1px solid rgba(255,255,255,0.06)", height: 60, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <Link href="/" style={{ textDecoration: "none", display: "flex", alignItems: "center", gap: 8 }}>
          <div style={{ width: 26, height: 26, borderRadius: 7, background: "linear-gradient(135deg,#7c3aed,#ec4899)", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>
          </div>
          <span style={{ fontWeight: 800, fontSize: "1rem", letterSpacing: "-0.02em", color: "rgba(255,255,255,0.95)" }}>Axiom</span>
        </Link>
        <Link href="/" style={{ fontSize: "0.82rem", color: "rgba(255,255,255,0.4)", textDecoration: "none" }}>← Back to home</Link>
      </nav>

      <main style={{ position: "relative", zIndex: 10, maxWidth: 720, margin: "0 auto", padding: "64px 24px 100px" }}>
        <p style={{ fontSize: "0.7rem", fontWeight: 700, letterSpacing: "0.18em", textTransform: "uppercase", color: "rgba(167,139,250,0.6)", marginBottom: 12 }}>Legal</p>
        <h1 style={{ fontSize: "2.4rem", fontWeight: 900, letterSpacing: "-0.025em", marginBottom: 8, color: "rgba(255,255,255,0.95)" }}>Terms of Service</h1>
        <p style={{ fontSize: "0.82rem", color: "rgba(255,255,255,0.25)", marginBottom: 52 }}>Last updated: March 2026</p>

        {[
          {
            title: "1. Acceptance of Terms",
            body: "By accessing or using Axiom, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service. We reserve the right to update these terms at any time, and your continued use of the service constitutes acceptance of any changes.",
          },
          {
            title: "2. Description of Service",
            body: "Axiom is a product intelligence layer that analyzes your build and surfaces risk areas, architecture recommendations, and execution paths based on user-submitted idea descriptions. The service is provided via our web application and powered in part by Anthropic's Claude AI.",
          },
          {
            title: "3. User Accounts",
            body: "You must create an account to use Axiom. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must provide accurate information when creating your account and keep it up to date.",
          },
          {
            title: "4. Acceptable Use",
            body: "You agree not to use Axiom to submit ideas that are illegal, harmful, or infringe on the rights of others. You may not attempt to reverse-engineer, scrape, or overload our systems. You may not use the service to generate content that promotes illegal activities, hate speech, or exploitation.",
          },
          {
            title: "5. AI-Generated Content",
            body: "The blueprints, recommendations, and build steps generated by Axiom are produced by AI and are for informational and planning purposes only. They do not constitute professional legal, financial, or technical advice. We make no guarantee that AI-generated content is accurate, complete, or suitable for your specific situation.",
          },
          {
            title: "6. Intellectual Property",
            body: "You retain ownership of the ideas you submit to Axiom. The generated blueprints are provided to you for your personal or commercial use. Axiom retains all rights to the platform, its design, and underlying technology. You may not copy or redistribute the Axiom application itself.",
          },
          {
            title: "7. Free Tier Limitations",
            body: "The free tier includes a limited number of blueprint generations per month. We reserve the right to modify, suspend, or discontinue the free tier at any time with reasonable notice. Exceeding usage limits may result in temporary suspension of access.",
          },
          {
            title: "8. Disclaimer of Warranties",
            body: "Axiom is provided 'as is' without warranty of any kind, express or implied. We do not warrant that the service will be uninterrupted, error-free, or that the results obtained from use of the service will be accurate or reliable.",
          },
          {
            title: "9. Limitation of Liability",
            body: "To the fullest extent permitted by law, Axiom shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service, including but not limited to loss of profits, business opportunity, or data.",
          },
          {
            title: "10. Contact",
            body: "For questions about these Terms of Service, please contact us at legal@axiom.com. We aim to respond to all inquiries within 5 business days.",
          },
        ].map(section => (
          <section key={section.title} style={{ marginBottom: 36 }}>
            <h2 style={{ fontSize: "1.05rem", fontWeight: 700, color: "rgba(255,255,255,0.85)", marginBottom: 10 }}>{section.title}</h2>
            <p style={{ fontSize: "0.88rem", color: "rgba(255,255,255,0.4)", lineHeight: 1.8, margin: 0 }}>{section.body}</p>
          </section>
        ))}

        <div style={{ marginTop: 52, paddingTop: 32, borderTop: "1px solid rgba(255,255,255,0.07)", display: "flex", gap: 20, flexWrap: "wrap" }}>
          <Link href="/privacy" style={{ fontSize: "0.82rem", color: "rgba(167,139,250,0.6)", textDecoration: "none" }}>Privacy Policy →</Link>
          <Link href="/" style={{ fontSize: "0.82rem", color: "rgba(255,255,255,0.25)", textDecoration: "none" }}>Back to home</Link>
        </div>
      </main>
    </div>
  );
}
